Single session for multiple group chats
meedan/tg-archive pull request #1
Opened 2023-11-05 18:20 UTC by eugenia0804

Added in helper.py and util.py.
Run helper.py to get fetched data from all group names in .xlsx
Change fetch_batch_size & fetch_limit to fetch more messages

2023-11-06 01:01 UTC, huslage requested changes

2023-11-06 01:01 UTC, huslage commented on helper.py
> +group_names = read_group_names("MASTER_NAWA_GAZA_Sources_2023_data_collecting.xlsx")
Could this be passed in as an argument on the CLI? What are the columns required in it?

2023-11-06 16:40 UTC, eugenia0804 commented on helper.py
> +group_names = read_group_names("MASTER_NAWA_GAZA_Sources_2023_data_collecting.xlsx")
Only the column Source ID is needed (urls with group names).

2023-11-06 17:00 UTC, huslage commented on helper.py
> +group_names = read_group_names("MASTER_NAWA_GAZA_Sources_2023_data_collecting.xlsx")
So could we just do a list of channel names in a text file instead of an XLS?

2023-11-07 21:33 UTC, eugenia0804 commented on helper.py
> +group_names = read_group_names("MASTER_NAWA_GAZA_Sources_2023_data_collecting.xlsx")
Yep

2023-11-17 02:16 UTC, closed without merging